### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by Hanros94** [GuanQunMu/IonTrap-WIPM#15]
I'm trying to follow the installation instructions to install IonTrap-WIPM.
In step 3 it states to copy the device_db.py file from M-lab however searching for this file in the art M-labs repository results in many different device_db.py files, I'm assuming I should choose the /examples/kasli/device_db.py

what is the meaning in step 6 to "copy the the folder repository to recover the same name folder in Artiq_WIPM"

Could you please advise me.

**Comment by GuanQunMu** [comment]
Thank you very much for asking me about your Queries.
I would like to reply in the simple way as follows:
1. If you have bought the hardware from M-Labs, use the device_db.py (this is normally provided by the supplier i.e M-Labs).
2. In contrast use the device_db.py, which is given in this project (however, in the current scenario you can't connect the device but can open the GUI etc.)
As for as the "step 6" is concerned, it is just a procedure to get uncompressed the uploaded Zipped repository folder.
I hope you will be clear about your asked queries. In case of any further problem, don't hesitate to contact me anytime. Furthermore, I would like to suggest, if you provide your contact information we may discuss it in more detail, please.

Wish you happy and healthy time.
Best Regards

Guanqun

**Comment by Hanros94** [comment]
Hi Guanqun

Many thanks for the help. I have download the zip file and copied the repository to the folder artiq_WIPM and tried to run artiq_main but I’m getting the error stating that artiq_main is not an internal or external command, operable program or batch file
Could you please advise me.
You mentioned contact information, what type did you have in mind?

Kind regards
Roshan



On 8 Jul 2020, at 12:18, GuanQun Mu <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much for asking me about your Queries.
I would like to reply in the simple way as follows:

  1.  If you have bought the hardware from M-Labs, use the device_db.py (this is normally provided by the supplier i.e M-Labs).
  2.  In contrast use the device_db.py, which is given in this project (however, in the current scenario you can't connect the device but can open the GUI etc.)
As for as the "step 6" is concerned, it is just a procedure to get uncompressed the uploaded Zipped repository folder.
I hope you will be clear about your asked queries. In case of any further problem, don't hesitate to contact me anytime. Furthermore, I would like to suggest, if you provide your contact information we may discuss it in more detail, please.

Wish you happy and healthy time.
Best Regards

Guanqun

**Comment by GuanQunMu** [comment]
Dear Roshan

Actually it is my mistake. I mistyped the command prompt in the README.md. It should be 'artiq_master' instead of 'artiq_main'. I have changed it in the introduction file and if you follow the latest procedure, the error won't appear.

thank you for pointing the mistake out. If you have any other problem, please be free to contact me.

Best regards 
Guanqun

**Comment by Hanros94** [comment]
Dear Guanqun

I’m unfortunately still getting the same error
“Artiq_master is not a recognised internal or external command, operable program or batch file.”

Do you think this may be a problem with my artiq installation.

Kind regards
Roshan


On 10 Jul 2020, at 07:42, GuanQun Mu <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Roshan

Actually it is my mistake. I mistyped the command prompt in the README.md. It should be 'artiq_master' instead of 'artiq_main'. I have changed it in the introduction file and if you follow the latest procedure, the error won't appear.

thank you for pointing the mistake out. If you have any other problem, please be free to contact me.

Best regards
Guanqun

**Comment by Hanros94** [comment]
Hi GuanQun

I have fixed the issue with Artiq_master however I'm still getting the following error. I had replaced the device_db.py witht the version from

Traceback (most recent call last):
  File "C:\Users\Roshan\.conda\envs\artiq\Scripts\artiq_master-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Roshan\.conda\envs\artiq\lib\site-packages\artiq\frontend\artiq_master.py", line 97, in main
    device_db = DeviceDB(args.device_db)
  File "C:\Users\Roshan\.conda\envs\artiq\lib\site-packages\artiq\master\databases.py", line 19, in __init__
    self.data = Notifier(device_db_from_file(self.backing_file))
  File "C:\Users\Roshan\.conda\envs\artiq\lib\site-packages\artiq\master\databases.py", line 11, in device_db_from_file
    with tokenize.open(filename) as f:
  File "C:\Users\Roshan\.conda\envs\artiq\lib\tokenize.py", line 454, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'device_db.py'

Could you please advise me.

Kind regards
Roshan
________________________________

**Comment by GuanQunMu** [comment]
Hi Roshan

Have you switched to the folder where this project is located with the command prompt?

I mean, you need to enter 'cd ...\IonTrap-WIPM-master' before entering 'artiq_master' , the '...\IonTrap-WIPM-master' is the address of this project folder in your PC, and inside the folder there should be a 'device.db' file.

After the terminal shows you that the address has been switched to this folder, you can execute the ‘artiq_master’ step and the error will disappear.

Best regards
Guanqun

**Comment by Hanros94** [comment]
Hi GuanQun

Thanks a lot for the help, you were right, my address was not right. There was another IonTrap-WIPM-master folder within the main IonTrap-WIPM-master folder IN MY CASE for some reason. Everything seems to be working now. Many thanks for the help.

Kind regards
Roshan
________________________________

**Comment by Hanros94** [comment]
Hi Guanqun

I'm trying to install the control system on another computer but the link in step 1 of "section 2 Usage" is broken. Could you please fix it.


Kind regards
Roshan

________________________________

**Comment by GuanQunMu** [comment]
Hi Roshan 

Actually the intallation step has been renewed by M-Labs, so please check the latest introduction provided by M-Labs :  https://m-labs.hk/artiq/manual/installing.html#installing-via-conda-windows-linux

Please go to the 'Installing via Conda (Windows, Linux)' part and follow what they gave. If it shows no problem, I will update the installation procedure in this project.

Best regards
Guanqun

**Comment by Hanros94** [comment]
Hi Guanqun

Sorry for the very late response but I have installed your project. I am trying to use artiq_client to submit the experiments in the repository folder to simply test the scheduling procedure and even if the submit experiment is given an RID number in the artiq_client window, in the artiq_master window there is an error which states that the file could not be found.  I supposed this was because artiq_master was called in the IonTrap-WIPM-master folder whereas artiq_client is working in the repository folder. I therefore moved the test file TTL397_test.py out of the repo folder into IonTrap_WIPM-master folder, and now running artiq_client submit TTL397_test.py gives the error seen below. It is the last error. Could you please advise me?

![image](https://user-images.githubusercontent.com/65071210/111324167-6edfa680-8662-11eb-8ff4-be16a53f52c6.png)

**Comment by Hanros94** [comment]
Hi Guanqun

Could you please tell me how you have connected the pushbutton 'Submit' to the submit function used in artiq_client or Artiq_dashboard? I have looked through the GUI .ui and .py files but I can't find any connections.
